language: node_js
node_js:
  - "stable"
script:
  - cd lanchonete-web
  - npm install
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  project: ./lanchonete-web/build
  on:
    branch: master
