export const SET_DATA = "SET_DATA";

export const SELECT_SANDWICH = "SELECT_SANDWICH";

export const CUSTOMIZE_SANDWICH = "CUSTOMIZE_SANDWICH";

export const CLOSE_CUSTOMIZE_SANDWICH = "CLOSE_CUSTOMIZE_SANDWICH";

export const REMOVE_INGREDIENT_SANDWICH = "REMOVE_INGREDIENT_SANDWICH";

export const ADD_INGREDIENT_SANDWICH = "ADD_INGREDIENT_SANDWICH";

export const ADD_SANDWICH_CART = "ADD_SANDWICH_CART";